src/Core.Web.Admin/Controllers/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Core.Web.Admin.Extensions;

namespace Core.Web.Admin.Controllers.Controllers
{
    public class HeaderViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var currentUser = HttpContext.GetCurrentUser();
            return View("Header", currentUser);
        }
        
    }
}

src/Core.Web.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1,user-scalable=no">
    <meta name="author" content="ARC Dev [www.anruichina.com]" />
    <meta name="description" content="Smart Event Management" />
    <meta name="keywords" content="云,ARC Dev,安锐卓越" />
    <link rel="shortcut icon" href='@Url.Content("~/favicon.ico")'>
    <title>小程序系统管理后台</title>
    <link rel="stylesheet" href="~/lib/LayUI/css/layui.css?v=20190219001" type="text/css" />
    @*<link rel="stylesheet" href="~/Scripts/LayUI/css/layui.mobile.css?v=20180925" type="text/css" />*@
    <link rel="stylesheet" href="~/lib/LayUI/layui-formSelects/formSelects-v4.css?v=2018-12-19-2" type="text/css" />
    <style>
        .layui-table-tool-self {
            display: none !important;
        }
    </style>
    @*@Scripts.Render("~/bundles/modernizr")*@

    <script>
        window.UrlBase = '@Url.Content("~/")';

    </script>
</head>
<body class="layui-layout-body">
    @RenderSection("styles", required: false)

    <div class="layui-layout layui-layout-admin">
        <!-- 页面头部-->
        @await Component.InvokeAsync("Header")
        <!--左侧菜单-->
        <div class="layui-side layui-bg-black">
            <div class="layui-side-scroll">

                @await Component.InvokeAsync("Menu")

            </div>
        </div>

        <!--主区域-->

        @RenderBody()



        <!--底部区域-->
        <div class="layui-footer" style="text-align:center">
            <!-- 底部固定区域 -->
            <p>小程序系统管理后台 </p>

        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/js/Common.js"></script>
    @*@Scripts.Render("~/bundles/jquery")*@

    <script type="text/javascript" src="~/lib/LayUI/layui.js?20180928"></script>
    <script type="text/javascript" src="~/lib/LayUI/layui.all.js?v=20180925"></script>

    <script type="text/javascript" charset="utf-8" src="~/lib/Neditor/neditor.config.js?v=2018112702"></script>
    <script type="text/javascript" charset="utf-8" src="~/lib/Neditor/neditor.all.min.js?v=20181212003"></script>
    <script type="text/javascript" charset="utf-8" src="~/lib/Neditor/neditor.service.js?v=201812170321"></script>
    <!--建议手动加在语言，避免在ie下有时因为加载语言失败导致编辑器加载失败-->
    <!--这里加载的语言文件会覆盖你在配置项目里添加的语言类型，比如你在配置项目里配置的是英文，这里加载的中文，那最后就是中文-->
    <script type="text/javascript" charset="utf-8" src="~/lib/Neditor/i18n/zh-cn/zh-cn.js"></script>
    <script type="text/javascript" charset="utf-8" src="~/lib/Neditor/third-party/browser-md5-file.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="@Url.Content("~/lib/layui/layui-formSelects/formSelects-v4.js")"></script>
    @RenderSection("scripts", required: false)
    <script>

        //JavaScript代码区域
        layui.use('element', function () {
            var element = layui.element;

        });


        //后台模块判断

        switch (getQueryString("type")) {
            case "docunemt":
                $(".layui-nav-item").removeClass("layui-nav-itemed");
                $(".layui-nav-item[data-type='docunemt']").addClass("layui-nav-itemed");
                break;
            case "active":
                $(".layui-nav-item").removeClass("layui-nav-itemed");
                $(".layui-nav-item[data-type='active']").addClass("layui-nav-itemed");
                break;
            case "user":
                $(".layui-nav-item").removeClass("layui-nav-itemed");
                $(".layui-nav-item[data-type='user']").addClass("layui-nav-itemed");
                break;
            case "category":
                $(".layui-nav-item").removeClass("layui-nav-itemed");
                $(".layui-nav-item[data-type='solution']").addClass("layui-nav-itemed");
                break;
            case "solution":
                $(".layui-nav-item").removeClass("layui-nav-itemed");
                $(".layui-nav-item[data-type='solution']").addClass("layui-nav-itemed");
                break;



        }

        function getQueryString(name) {
            var reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)", "i");
            var r = window.location.search.substr(1).match(reg);
            if (r != null)
                return unescape(r[2]);
            return null;
        }
    </script>
</body>
</html>